# ============================
# Spring Application Settings
# ============================
SERVER_PORT: 8084
SPRING_PROFILES_ACTIVE: local

  # ============================
  # PostgreSQL Configuration
# ============================
POSTGRES_DB: upaguru
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_URL: jdbc:postgresql://localhost:5432/upaguru

  # ============================
  # MongoDB Configuration
# ============================
MONGO_URL: mongodb://localhost:27017/upaguru
MONGO_DB: upaguru

  # ============================
  # OpenAI Configuration
# ============================
OPENAI_API_KEY: sk-proj-
OPENAI_MODEL: gpt-4
OPENAI_API_URL: "https://api.openai.com/v1/chat/completions"